services:
  - type: web
    name: medicare
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate --noinput"
    startCommand: "gunicorn healthstack.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false