services:
  - type: web
    name: medicare
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn healthstack.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: medicare-db
          property: connectionString
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend

databases:
  - name: medicare-db
    databaseName: medicare
    user: medicare
