# Generated by Django 4.1.13 on 2024-01-12 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_admin', '__first__'),
        ('hospital', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Information',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('department', models.CharField(blank=True, choices=[('Cardiologists', 'Cardiologists'), ('Neurologists', 'Neurologists'), ('Pediatricians', 'Pediatricians'), ('Physiatrists', 'Physiatrists'), ('Dermatologists', 'Dermatologists')], max_length=200, null=True)),
                ('featured_image', models.ImageField(blank=True, default='doctors/user-default.png', null=True, upload_to='doctors/')),
                ('certificate_image', models.ImageField(blank=True, default='doctors_certificate/default.png', null=True, upload_to='doctors_certificate/')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('nid', models.CharField(blank=True, max_length=200, null=True)),
                ('visiting_hour', models.CharField(blank=True, max_length=200, null=True)),
                ('consultation_fee', models.IntegerField(blank=True, null=True)),
                ('report_fee', models.IntegerField(blank=True, null=True)),
                ('dob', models.CharField(blank=True, max_length=200, null=True)),
                ('institute', models.CharField(blank=True, max_length=200, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('completion_year', models.CharField(blank=True, max_length=200, null=True)),
                ('work_place', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('start_year', models.CharField(blank=True, max_length=200, null=True)),
                ('end_year', models.CharField(blank=True, max_length=200, null=True)),
                ('register_status', models.CharField(blank=True, max_length=200, null=True)),
                ('department_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_admin.hospital_department')),
                ('hospital_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.hospital_information')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_admin.specialization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.CharField(blank=True, max_length=200, null=True)),
                ('medicine_name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.CharField(blank=True, max_length=200, null=True)),
                ('days', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
                ('relation_with_meal', models.CharField(blank=True, max_length=200, null=True)),
                ('medicine_description', models.TextField(blank=True, null=True)),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('test_description', models.TextField(blank=True, null=True)),
                ('extra_information', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_information')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription_test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('test_description', models.TextField(blank=True, null=True)),
                ('test_info_id', models.CharField(blank=True, max_length=200, null=True)),
                ('test_info_price', models.CharField(blank=True, max_length=200, null=True)),
                ('test_info_pay_status', models.CharField(blank=True, max_length=200, null=True)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('specimen_id', models.CharField(blank=True, max_length=200, null=True)),
                ('specimen_type', models.CharField(blank=True, max_length=200, null=True)),
                ('collection_date', models.CharField(blank=True, max_length=200, null=True)),
                ('receiving_date', models.CharField(blank=True, max_length=200, null=True)),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('referred_value', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_date', models.CharField(blank=True, max_length=200, null=True)),
                ('other_information', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor_information')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='testCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=200)),
                ('purchased', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription_test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='testOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(blank=True, max_length=200, null=True)),
                ('trans_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('orderitems', models.ManyToManyField(to='doctor.testcart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('referred_value', models.CharField(blank=True, max_length=200, null=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.report')),
            ],
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('specimen_id', models.AutoField(primary_key=True, serialize=False)),
                ('specimen_type', models.CharField(blank=True, max_length=200, null=True)),
                ('collection_date', models.CharField(blank=True, max_length=200, null=True)),
                ('receiving_date', models.CharField(blank=True, max_length=200, null=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.report')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription_medicine',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('frequency', models.CharField(blank=True, max_length=200, null=True)),
                ('relation_with_meal', models.CharField(blank=True, max_length=200, null=True)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_place_name', models.CharField(blank=True, max_length=200, null=True)),
                ('from_year', models.CharField(blank=True, max_length=200, null=True)),
                ('to_year', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_information')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('institute', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_completion', models.CharField(blank=True, max_length=200, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_information')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_information')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
                ('appointment_type', models.CharField(choices=[('report', 'report'), ('checkup', 'checkup')], max_length=200)),
                ('appointment_status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_status', models.CharField(blank=True, default='pending', max_length=200, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor_information')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
